class Constant:
    BODY = 'Body'
    BUCKET_ROOT = ''
    CONTENTS = 'Contents'
    DOT = '.'
    KEY = 'Key'
    LINE_BREAK = '\n'
    PATH_SEPARATOR = '/'

    MERGED_FILE_CHUNK_DEFAULT_SIZE_IN_MB = 10
    IS_SUCCESS_FILES_DELETION_ENABLED = True
    IS_FILES_TO_MERGE_DELETION_ENABLED = True

    SUCCESS_NO_EXTENSION = '_SUCCESS'
    SUCCESS_WITH_CRC_EXTENSION = f'.{SUCCESS_NO_EXTENSION}.crc'
